services:

  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-bot
    env_file:
      - ./.env
    volumes:
      - ./log:/app/log
      - ./db:/app/db
